package ai.passman.pgp.utils

import org.bouncycastle.openpgp.PGPUtil
import java.io.ByteArrayInputStream
import java.io.EOFException
import java.io.InputStream

/**
 * Whether this build can make sense of a key ring, decided by reading the raw packets rather than
 * by asking BouncyCastle.
 *
 * BC is deliberately forgiving about algorithms it does not know, and each of its three behaviours
 * is invisible from the parsed object graph:
 *
 * - A **v4 primary** with an unknown algorithm throws `IOException` out of `PGPObjectFactory`,
 *   which the key listing catches and logs, so the file simply never appears.
 * - A **v4 subkey** with an unknown algorithm is dropped with a `LOG.fine` and the ring reports
 *   success — and because the dropped subkey's signature packets are left unread, every *later*
 *   subkey is silently lost too. The ring looks whole and is not.
 * - A **v6 key** with an unknown algorithm is accepted outright as an opaque blob, with a
 *   `bitStrength` derived from the raw material length. This is the case that matters for the
 *   post-quantum algorithms of RFC 9580, which require v6: such a key lists as a normal entry,
 *   reports thousands of "bits", and fails only later with a generic error.
 *
 * Reading the packet headers ourselves catches all three with one pass, and reports the algorithm
 * id so the user is told what their key actually uses instead of "import failed".
 */
sealed interface PgpKeyRingSupport {

    /** Every key and subkey uses an algorithm this build understands. */
    data object Supported : PgpKeyRingSupport

    /**
     * At least one key or subkey uses [algorithmId], which this build cannot use. The first
     * unsupported id encountered wins; a ring usually has only one novel algorithm in it.
     */
    data class UnsupportedAlgorithm(val algorithmId: Int) : PgpKeyRingSupport

    /** Not an OpenPGP key ring at all — wrong file, truncated download, armor over a message. */
    data object NotAKeyRing : PgpKeyRingSupport
}

/**
 * OpenPGP public-key algorithm ids this build understands, which is exactly the set the pinned
 * BouncyCastle can turn into a usable key. Anything outside it — the 100..110 private/experimental
 * range included — is another implementation's business, not ours.
 */
private val SUPPORTED_ALGORITHMS = setOf(
    1, 2, 3, // RSA (general, encrypt-only, sign-only)
    16, 20, // ElGamal
    17, // DSA
    18, // ECDH
    19, // ECDSA
    21, // Diffie-Hellman
    22, // EdDSA legacy (Ed25519 as generated by this app)
    23, 24, // AEDH / AEDSA
    25, 26, // X25519, X448
    27, 28, // Ed25519, Ed448
)

// Packet tags that carry a public-key algorithm byte. Tags 5/7 are the secret-key forms, which
// begin with the same public-key packet body.
private const val TAG_SECRET_KEY = 5
private const val TAG_PUBLIC_KEY = 6
private const val TAG_SECRET_SUBKEY = 7
private const val TAG_PUBLIC_SUBKEY = 14

private val KEY_PACKET_TAGS = setOf(TAG_SECRET_KEY, TAG_PUBLIC_KEY, TAG_SECRET_SUBKEY, TAG_PUBLIC_SUBKEY)

/** Offset of the algorithm byte within a key packet body, by key version. */
private const val ALGORITHM_OFFSET_V3 = 7 // version, creation (4), validity (2)
private const val ALGORITHM_OFFSET_V4 = 5 // version, creation (4)

/**
 * Reads [source] — armored or binary — and reports whether this build can use every key in it.
 *
 * Never throws: a stream that cannot be read at all is [PgpKeyRingSupport.NotAKeyRing], which is
 * the honest answer for the caller either way.
 */
fun inspectKeyRingSupport(source: InputStream): PgpKeyRingSupport = runCatching {
    val packets = PGPUtil.getDecoderStream(source).use { it.readBytes() }
    inspectKeyRingPackets(packets)
}.getOrElse { PgpKeyRingSupport.NotAKeyRing }

/** [inspectKeyRingSupport] over bytes already in hand. */
fun inspectKeyRingSupport(bytes: ByteArray): PgpKeyRingSupport =
    inspectKeyRingSupport(ByteArrayInputStream(bytes))

private fun inspectKeyRingPackets(packets: ByteArray): PgpKeyRingSupport {
    val reader = PacketReader(packets)
    var sawKeyPacket = false

    while (true) {
        val packet = reader.next() ?: break
        if (packet.tag !in KEY_PACKET_TAGS) continue
        sawKeyPacket = true

        val algorithm = packet.algorithmId() ?: return PgpKeyRingSupport.NotAKeyRing
        if (algorithm !in SUPPORTED_ALGORITHMS) {
            return PgpKeyRingSupport.UnsupportedAlgorithm(algorithm)
        }
    }

    return if (sawKeyPacket) PgpKeyRingSupport.Supported else PgpKeyRingSupport.NotAKeyRing
}

private class Packet(val tag: Int, val body: ByteArray) {

    /**
     * The algorithm byte, or null if the body is too short or the version is one nobody has
     * defined. v4, v5 (LibrePGP) and v6 all place it directly after the 4-byte creation time;
     * only v2/v3 differ, by carrying a validity period first.
     */
    fun algorithmId(): Int? {
        val version = body.firstOrNull()?.toInt()?.and(0xFF) ?: return null
        val offset = when (version) {
            2, 3 -> ALGORITHM_OFFSET_V3
            4, 5, 6 -> ALGORITHM_OFFSET_V4
            else -> return null
        }
        return body.getOrNull(offset)?.toInt()?.and(0xFF)
    }
}

/**
 * A minimal OpenPGP packet-header walker: enough to find key packets and their algorithm byte,
 * and deliberately no more. It reads only headers and skips bodies wholesale, so a packet body it
 * does not understand costs nothing.
 */
private class PacketReader(private val bytes: ByteArray) {

    private var position = 0

    /** The next packet, or null at end of input. Throws [EOFException] on a truncated header. */
    fun next(): Packet? {
        if (position >= bytes.size) return null

        val header = readByte()
        // Bit 7 is set on every packet header. Anything else means we have lost sync, and guessing
        // from here would be worse than stopping.
        if (header and 0x80 == 0) throw EOFException("not a packet header")

        val newFormat = header and 0x40 != 0
        val tag = if (newFormat) header and 0x3F else (header shr 2) and 0x0F
        val length = if (newFormat) newFormatLength() else oldFormatLength(header and 0x03)

        // An indeterminate or partial length is legal only on data packets, never on a key packet.
        // Treat it as the end of anything we can reason about.
        if (length == null) return null

        val end = position + length
        if (length < 0 || end > bytes.size) throw EOFException("packet runs past end of input")
        val body = bytes.copyOfRange(position, end)
        position = end
        return Packet(tag, body)
    }

    private fun readByte(): Int {
        if (position >= bytes.size) throw EOFException("truncated packet header")
        return bytes[position++].toInt() and 0xFF
    }

    private fun oldFormatLength(lengthType: Int): Int? = when (lengthType) {
        0 -> readByte()
        1 -> (readByte() shl 8) or readByte()
        2 -> (readByte() shl 24) or (readByte() shl 16) or (readByte() shl 8) or readByte()
        else -> null // indeterminate: runs to end of input
    }

    private fun newFormatLength(): Int? {
        val first = readByte()
        return when {
            first < 192 -> first
            first < 224 -> ((first - 192) shl 8) + readByte() + 192
            first == 255 -> (readByte() shl 24) or (readByte() shl 16) or (readByte() shl 8) or readByte()
            else -> null // partial body length
        }
    }
}
